/**
 * Created by Alexander Melashchenko on 4/3/17.
 */

const CREATE_REQUEST = 'CREATE_REQUEST';
const CREATE_SUCCESS = 'CREATE_SUCCESS';
const CREATE_FAILED = 'CREATE_FAILED';

const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAILED = 'GET_FAILED';

const GET_ONE_REQUEST = 'GET_ONE_REQUEST';
const GET_ONE_SUCCESS = 'GET_ONE_SUCCESS';
const GET_ONE_FAILED = 'GET_ONE_FAILED';

const SEARCH_REQUEST = 'SEARCH_REQUEST';
const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
const SEARCH_FAILED = 'SEARCH_FAILED';

const UPDATE_REQUEST = 'UPDATE_REQUEST';
const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
const UPDATE_FAILED = 'UPDATE_FAILED';

const DELETE_REQUEST = 'DELETE_REQUEST';
const DELETE_SUCCESS = 'DELETE_SUCCESS';
const DELETE_FAILED = 'DELETE_FAILED';

export {
    CREATE_REQUEST,
    CREATE_SUCCESS,
    CREATE_FAILED,
    GET_REQUEST,
    GET_SUCCESS,
    GET_FAILED,
    GET_ONE_REQUEST,
    GET_ONE_SUCCESS,
    GET_ONE_FAILED,
    SEARCH_REQUEST,
    SEARCH_SUCCESS,
    SEARCH_FAILED,
    UPDATE_REQUEST,
    UPDATE_SUCCESS,
    UPDATE_FAILED,
    DELETE_REQUEST,
    DELETE_SUCCESS,
    DELETE_FAILED,
}