/**
 * Created by Alexander Melashchenko on 4/1/17.
 */

const CREATE_HORSE_REQUEST = 'CREATE_HORSE_REQUEST';
const CREATE_HORSE_SUCCESS = 'CREATE_HORSE_SUCCESS';
const CREATE_HORSE_FAILED = 'CREATE_HORSE_FAILED';

const GET_HORSES_REQUEST = 'GET_HORSES_REQUEST';
const GET_HORSES_SUCCESS = 'GET_HORSES_SUCCESS';
const GET_HORSES_FAILED = 'GET_HORSES_FAILED';

const UPDATE_HORSE_REQUEST = 'UPDATE_HORSE_REQUEST';
const UPDATE_HORSE_SUCCESS = 'UPDATE_HORSE_SUCCESS';
const UPDATE_HORSE_FAILED = 'UPDATE_HORSE_FAILED';

const DELETE_HORSE_REQUEST = 'UPDATE_HORSE_REQUEST';
const DELETE_HORSE_SUCCESS = 'UPDATE_HORSE_SUCCESS';
const DELETE_HORSE_FAILED = 'UPDATE_HORSE_FAILED';

export {
    CREATE_HORSE_REQUEST,
    CREATE_HORSE_SUCCESS,
    CREATE_HORSE_FAILED,
    GET_HORSES_REQUEST,
    GET_HORSES_SUCCESS,
    GET_HORSES_FAILED,
    DELETE_HORSE_REQUEST,
    DELETE_HORSE_SUCCESS,
    DELETE_HORSE_FAILED
}
