/**
 * Created by Alexander Melashchenko on 4/1/17.
 */

const CREATE_JOCKEY_REQUEST = 'CREATE_JOCKEY_REQUEST';
const CREATE_JOCKEY_SUCCESS = 'CREATE_JOCKEY_SUCCESS';
const CREATE_JOCKEY_FAILED = 'CREATE_JOCKEY_FAILED';

const GET_JOCKEYS_REQUEST = 'GET_JOCKEYS_REQUEST';
const GET_JOCKEYS_SUCCESS = 'GET_JOCKEYS_SUCCESS';
const GET_JOCKEYS_FAILED = 'GET_JOCKEYS_FAILED';

const SEARCH_JOCKEYS_REQUEST = 'SEARCH_JOCKEYS_REQUEST';
const SEARCH_JOCKEYS_SUCCESS = 'SEARCH_JOCKEYS_SUCCESS';
const SEARCH_JOCKEYS_FAILED = 'SEARCH_JOCKEYS_FAILED';

const UPDATE_JOCKEY_REQUEST = 'UPDATE_JOCKEY_REQUEST';
const UPDATE_JOCKEY_SUCCESS = 'UPDATE_JOCKEY_SUCCESS';
const UPDATE_JOCKEY_FAILED = 'UPDATE_JOCKEY_FAILED';

const DELETE_JOCKEY_REQUEST = 'UPDATE_JOCKEY_REQUEST';
const DELETE_JOCKEY_SUCCESS = 'UPDATE_JOCKEY_SUCCESS';
const DELETE_JOCKEY_FAILED = 'UPDATE_JOCKEY_FAILED';

export {
    CREATE_JOCKEY_REQUEST,
    CREATE_JOCKEY_SUCCESS,
    CREATE_JOCKEY_FAILED,
    GET_JOCKEYS_REQUEST,
    GET_JOCKEYS_SUCCESS,
    GET_JOCKEYS_FAILED,
    SEARCH_JOCKEYS_REQUEST,
    SEARCH_JOCKEYS_SUCCESS,
    SEARCH_JOCKEYS_FAILED,
    UPDATE_JOCKEY_REQUEST,
    UPDATE_JOCKEY_SUCCESS,
    UPDATE_JOCKEY_FAILED,
    DELETE_JOCKEY_REQUEST,
    DELETE_JOCKEY_SUCCESS,
    DELETE_JOCKEY_FAILED
}
