/**
 * Created by Alexander Melashchenko on 4/1/17.
 */

const CREATE_OWNER_REQUEST = 'CREATE_OWNER_REQUEST';
const CREATE_OWNER_SUCCESS = 'CREATE_OWNER_SUCCESS';
const CREATE_OWNER_FAILED = 'CREATE_OWNER_FAILED';

const GET_OWNERS_REQUEST = 'GET_OWNERS_REQUEST';
const GET_OWNERS_SUCCESS = 'GET_OWNERS_SUCCESS';
const GET_OWNERS_FAILED = 'GET_OWNERS_FAILED';

const SEARCH_OWNERS_REQUEST = 'SEARCH_OWNERS_REQUEST';
const SEARCH_OWNERS_SUCCESS = 'SEARCH_OWNERS_SUCCESS';
const SEARCH_OWNERS_FAILED = 'SEARCH_OWNERS_FAILED';

const UPDATE_OWNER_REQUEST = 'UPDATE_OWNER_REQUEST';
const UPDATE_OWNER_SUCCESS = 'UPDATE_OWNER_SUCCESS';
const UPDATE_OWNER_FAILED = 'UPDATE_OWNER_FAILED';

const DELETE_OWNER_REQUEST = 'UPDATE_OWNER_REQUEST';
const DELETE_OWNER_SUCCESS = 'UPDATE_OWNER_SUCCESS';
const DELETE_OWNER_FAILED = 'UPDATE_OWNER_FAILED';

export {
    CREATE_OWNER_REQUEST,
    CREATE_OWNER_SUCCESS,
    CREATE_OWNER_FAILED,
    GET_OWNERS_REQUEST,
    GET_OWNERS_SUCCESS,
    GET_OWNERS_FAILED,
    SEARCH_OWNERS_REQUEST,
    SEARCH_OWNERS_SUCCESS,
    SEARCH_OWNERS_FAILED,
    UPDATE_OWNER_REQUEST,
    UPDATE_OWNER_SUCCESS,
    UPDATE_OWNER_FAILED,
    DELETE_OWNER_REQUEST,
    DELETE_OWNER_SUCCESS,
    DELETE_OWNER_FAILED
}
