/**
 * Created by Alexander Melashchenko on 4/1/17.
 */

const CREATE_RACE_REQUEST = 'CREATE_RACE_REQUEST';
const CREATE_RACE_SUCCESS = 'CREATE_RACE_SUCCESS';
const CREATE_RACE_FAILED = 'CREATE_RACE_FAILED';

const GET_RACES_REQUEST = 'GET_RACES_REQUEST';
const GET_RACES_SUCCESS = 'GET_RACES_SUCCESS';
const GET_RACES_FAILED = 'GET_RACES_FAILED';

const UPDATE_RACE_REQUEST = 'UPDATE_RACE_REQUEST';
const UPDATE_RACE_SUCCESS = 'UPDATE_RACE_SUCCESS';
const UPDATE_RACE_FAILED = 'UPDATE_RACE_FAILED';

const DELETE_RACE_REQUEST = 'UPDATE_RACE_REQUEST';
const DELETE_RACE_SUCCESS = 'UPDATE_RACE_SUCCESS';
const DELETE_RACE_FAILED = 'UPDATE_RACE_FAILED';

export {
    CREATE_RACE_REQUEST,
    CREATE_RACE_SUCCESS,
    CREATE_RACE_FAILED,
    GET_RACES_REQUEST,
    GET_RACES_SUCCESS,
    GET_RACES_FAILED,
    DELETE_RACE_REQUEST,
    DELETE_RACE_SUCCESS,
    DELETE_RACE_FAILED
}
