/**
 * Created by melalex on 4/10/17.
 */

const RACE_UPDATE_REQUEST = 'RACE_UPDATE_REQUEST';
const RACE_UPDATE_SUCCESS = 'RACE_UPDATE_SUCCESS';
const RACE_UPDATE_FAILED = 'RACE_UPDATE_FAILED';

export {
    RACE_UPDATE_REQUEST,
    RACE_UPDATE_SUCCESS,
    RACE_UPDATE_FAILED
}