/**
 * Created by Alexander Melashchenko on 4/1/17.
 */

const CREATE_RACECOURSE_REQUEST = 'CREATE_RACECOURSE_REQUEST';
const CREATE_RACECOURSE_SUCCESS = 'CREATE_RACECOURSE_SUCCESS';
const CREATE_RACECOURSE_FAILED = 'CREATE_RACECOURSE_FAILED';

const GET_RACECOURSES_REQUEST = 'GET_RACECOURSES_REQUEST';
const GET_RACECOURSES_SUCCESS = 'GET_RACECOURSES_SUCCESS';
const GET_RACECOURSES_FAILED = 'GET_RACECOURSES_FAILED';

const UPDATE_RACECOURSE_REQUEST = 'UPDATE_RACECOURSE_REQUEST';
const UPDATE_RACECOURSE_SUCCESS = 'UPDATE_RACECOURSE_SUCCESS';
const UPDATE_RACECOURSE_FAILED = 'UPDATE_RACECOURSE_FAILED';

const DELETE_RACECOURSE_REQUEST = 'UPDATE_RACECOURSE_REQUEST';
const DELETE_RACECOURSE_SUCCESS = 'UPDATE_RACECOURSE_SUCCESS';
const DELETE_RACECOURSE_FAILED = 'UPDATE_RACECOURSE_FAILED';

export {
    CREATE_RACECOURSE_REQUEST,
    CREATE_RACECOURSE_SUCCESS,
    CREATE_RACECOURSE_FAILED,
    GET_RACECOURSES_REQUEST,
    GET_RACECOURSES_SUCCESS,
    GET_RACECOURSES_FAILED,
    DELETE_RACECOURSE_REQUEST,
    DELETE_RACECOURSE_SUCCESS,
    DELETE_RACECOURSE_FAILED
}
