/**
 * Created by Alexander Melashchenko on 4/1/17.
 */

const CREATE_TRAINER_REQUEST = 'CREATE_TRAINER_REQUEST';
const CREATE_TRAINER_SUCCESS = 'CREATE_TRAINER_SUCCESS';
const CREATE_TRAINER_FAILED = 'CREATE_TRAINER_FAILED';

const GET_TRAINERS_REQUEST = 'GET_TRAINERS_REQUEST';
const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
const GET_TRAINERS_FAILED = 'GET_TRAINERS_FAILED';

const SEARCH_TRAINERS_REQUEST = 'SEARCH_TRAINERS_REQUEST';
const SEARCH_TRAINERS_SUCCESS = 'SEARCH_TRAINERS_SUCCESS';
const SEARCH_TRAINERS_FAILED = 'SEARCH_TRAINERS_FAILED';

const UPDATE_TRAINER_REQUEST = 'UPDATE_TRAINER_REQUEST';
const UPDATE_TRAINER_SUCCESS = 'UPDATE_TRAINER_SUCCESS';
const UPDATE_TRAINER_FAILED = 'UPDATE_TRAINER_FAILED';

const DELETE_TRAINER_REQUEST = 'UPDATE_TRAINER_REQUEST';
const DELETE_TRAINER_SUCCESS = 'UPDATE_TRAINER_SUCCESS';
const DELETE_TRAINER_FAILED = 'UPDATE_TRAINER_FAILED';

export {
    CREATE_TRAINER_REQUEST,
    CREATE_TRAINER_SUCCESS,
    CREATE_TRAINER_FAILED,
    GET_TRAINERS_REQUEST,
    GET_TRAINERS_SUCCESS,
    GET_TRAINERS_FAILED,
    SEARCH_TRAINERS_REQUEST,
    SEARCH_TRAINERS_SUCCESS,
    SEARCH_TRAINERS_FAILED,
    UPDATE_TRAINER_REQUEST,
    UPDATE_TRAINER_SUCCESS,
    UPDATE_TRAINER_FAILED,
    DELETE_TRAINER_REQUEST,
    DELETE_TRAINER_SUCCESS,
    DELETE_TRAINER_FAILED
}
